### PR TITLE
fix PythonBufferErrorCode issue

### PR DESCRIPTION
**Pull request by ShigekiKarita**

### CODE REVIEW

**Comment by ShigekiKarita** [comment]
without this fix, `cannot_create_f_contiguous_buffer` is not found because it lacks of `typeof(return).`

```
dub test --build=unittest-cov                                                                                                                                 
Generating test runner configuration 'mir-algorithm-test-default' for 'default' (library).                                                                                                                      
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847                                                                                                                        
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847                                                                                                                        
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847                                                                                                                        
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847                                                                                                                        
Performing "unittest-cov" build using /home/skarita/dlang/dmd-2.083.0/linux/bin64/dmd for x86_64.                                                                                                               
mir-core 0.0.11: target for configuration "library" is up to date.                                                                                                                                              
mir-algorithm 0.6.13+commit.306.ga6fb479: building configuration "mir-algorithm-test-default"...                                                                                                                
Warning: multivariate cubic spline with derivatives was not tested!!!                                                                                                                                           
Warning: multivariate cubic spline with derivatives was not tested!!!                                                                                                                                           
source/mir/ndslice/connect/cpython.d(163,28): Error: undefined identifier cannot_create_f_contiguous_buffer                                                                                                     
source/mir/ndslice/connect/cpython.d(229,46): Error: template instance `mir.ndslice.connect.cpython.toPythonBuffer!(double, 2LU, cast(mir_slice_kind)2)` error instantiating                                    
source/mir/ndslice/connect/cpython.d(244,20):        instantiated from here: bar!cast(mir_slice_kind)2  
```

**Comment by 9il** [comment]
Thanks!

**Comment by 9il** [comment]
v3.1.9
