### ISSUE TITLE
cannot compile createRC with custom dtor class

### ISSUE THREAD

**Issue by ShigekiKarita** [libmir/mir-algorithm#208]
When I inserted custom dtor `~this() nothrow {}` to the existing class in unittest, it failed.
https://github.com/libmir/mir-algorithm/blob/c316ed2c89b474332da4ecf4fc1722189b965da8/source/mir/rc/ptr.d#L248-L253
```
dub test
Generating test runner configuration 'mir-algorithm-test-default' for 'default' (library).
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Performing "unittest" build using /home/karita/dlang/dmd-2.087.0/linux/bin64/dmd for x86_64.
mir-core 0.3.5: target for configuration "library" is up to date.
mir-algorithm 3.5.0-alpha11: building configuration "mir-algorithm-test-default"...
Warning: multivariate cubic spline with derivatives was not tested!!!
Warning: multivariate cubic spline with derivatives was not tested!!!
source/mir/type_info.d(72,29): Error: function object.destroy!(true, C).destroy is not nothrow
source/mir/type_info.d(59,21): Error: nothrow function mir.type_info.mir_get_type_info!(C).mir_get_type_info.destroy_impl may throw
source/mir/rc/ptr.d(128,42): Error: template instance `mir.type_info.mir_get_type_info!(C)` error instantiating
source/mir/rc/ptr.d(225,27):        instantiated from here: __ctor!int
source/mir/rc/ptr.d(256,24):        instantiated from here: createRC!int
/home/karita/dlang/dmd-2.087.0/linux/bin64/dmd failed with exit code 1.
```

I do not know why this happened because everything seems to be nothrow.
- `destroy` is ok because it is template just calling `rt_finalize` https://github.com/dlang/druntime/blob/3ba98e659dc6857d7f5ad6383adc2b02510ce597/src/object.d#L628
- `rt_finalize` is also nothrow https://github.com/dlang/druntime/blob/8a5e6f2fe878d9470a39ebee2574892370af5e01/src/rt/lifetime.d#L1423

@9il  Do you have any idea or workaround to call `createRC` with the class having custom dtor?

**Comment by ShigekiKarita** [comment]
I found the bug in the `object`. It seems to have the wrong declaration here.
https://github.com/dlang/druntime/blob/3ba98e659dc6857d7f5ad6383adc2b02510ce597/src/object.d#L990-L991

**Comment by ShigekiKarita** [comment]
I also found the workaround for this bug. We can put the correct declaration in `mir/type_info.d` and directly call `rt_finalize` as same as `destroy`.

**Comment by 9il** [comment]
DRuntiem Issue https://issues.dlang.org/show_bug.cgi?id=20049

**Comment by 9il** [comment]
All destructors that are used in Mir RC types should be `nothrow`. In the same time, there is no warranty that common D destructor is `nothrow`, this is why `rt_finalize` does not have any attributes.

As a workaround for this DRuntieme issue, I would suggest marking all user classes and interfaces with `extern(C++)` and optionally their members as `extern(D):`. Then the `destroy` function would not use  `rt_finalize`

**Comment by ShigekiKarita** [comment]
I see. Because throwing an exception in dtor is unsafe for unwinding stack, the [rt_finalize](https://github.com/dlang/druntime/blob/8a5e6f2fe878d9470a39ebee2574892370af5e01/src/rt/lifetime.d#L1412-L1416) converts exceptions to FinalizeError. So I think `rt_finalize`  can be nothrow.

Thanks to your workaround, my use case seems to be working.
